---
title: Jekyll Starter
timezone: UTC
collections:
  partners:
    title: Partners
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- "/vendor/"
- "/node_modules/"
- "/assets/_src_img/"
- Gemfile
- Gemfile.lock
- gulpfile.js
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: A template to get started on
url: ''
baseurl: ''
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
prose:
  media: media
  metadata:
    _partners:
    - name: layout
      field:
        element: hidden
        value: blog
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Choose Tags
        options:
        - name: Apples
          value: apples
        - name: Bananas
          value: bananas
    - name: permalink
      field:
        element: text
        label: Permalink
        value: ''
